### ISSUE TITLE
Couldn't connect to host: IP:5555, error: No such file or directory

### ISSUE THREAD

**Issue by BnMcG** [JeffLIrion/homeassistant_native_firetv#12]
Hi,

I'm trying to set this up on Hassbian, using the latest version of native_firetv pulled from the repo's master branch today, and HA 0.79.3.

Here's my config:

```
media_player:
  - platform: firetv
    name: Fire TV 1
    host: 192.168.0.11
    adbkey: "/home/homeassistant/.homeassistant/android/adbkey"
```

I can ping the Fire TV on this IP fine, ADB is enabled on the TV, and I've pre-authorized the key by generating from my laptop and then copying adbkey to the path above. I've confirmed that the key should be allowed on the Fire TV, and checked the "Always" box.

Permissions on the key file:

```
-rw-r--r--  1 homeassistant homeassistant 1704 Oct  6 21:46 adbkey
```

Log messages that appear in the HA UI:

```
Couldn't connect to host: 192.168.0.11:5555, error: No such file or directory

Could not connect to Fire TV at 192.168.0.11:5555 using adbkey='/home/homeassistant/.homeassistant/android/adbkey'

Found malformed XML at http://192.168.0.11:9080: status=ok
```

Anything I can do to help fix this? I've tried restarting the Fire TV and HA several times.
