### ISSUE TITLE
Can this be integrated with the new official ABD addon by Frenck?

### ISSUE THREAD

**Issue by 2016for** [JeffLIrion/homeassistant_native_firetv#23]
I am using the androidtv custom_component with official adb addon by Frenck (https://community.home-assistant.io/t/community-hass-io-add-on-adb-android-debug-bridge/96375)
Stability of connection is amazing.

The official FireTV component didn't work for me. Always showed Unavailable (with one or two state changes in b/w)

AndroidTV custom_component doesn't seem to be recognizing play/pause/idle or the current track playing on FireTV cube.

Would be amazing if stability of adb addon can be combined with firetv specific code.

Thanks

**Comment by JeffLIrion** [comment]
Yes. Use this branch: [firetv.py](
https://github.com/JeffLIrion/homeassistant_native_firetv/blob/pure-python-adb/media_player/firetv.py)

```yaml
media_player:
  - platform: firetv
    name: Fire TV
    host: 192.168.0.111
    adb_server_ip: 127.0.0.1
```
